In [5]:
import pandas as pd

In [51]:
def process_id(frame):
    index = frame.index.to_series().str.strip()
    index = index.str.replace(" ", "-")
    frame.set_index(index, inplace=True)
    return frame

In [62]:
caa = pd.read_excel("../../data/input/caa_courses.xlsx", index_col = "caa_course_id")
eq = pd.read_excel("../output/equivalencies2.xlsx", index_col = "caa_id")
eq = process_id(eq)
caa = process_id(caa)
known = pd.read_excel("../output/known.xlsx", index_col = "caa_id")
eq = eq.reset_index().drop_duplicates(subset='caa_id', keep='last').set_index('caa_id').sort_index()
eq

,caa_title,uncg_id,uncg_title
caa_id,,,
ACA-122,COLLEGE TRANSFER SUCCESS (1),ELE 000,FREE ELECTIVE CREDIT
ACA122,OLLEGE TRANSFER SUCCESS (1),ELE 000,FREE ELECTIVE CREDIT
ACC-120,PRINCIPLES OF FINANCIAL ACCOUNTIN (4),ACC 201,FINANCIAL ACCOUNTING
ACC-121,PRINCIPLES OF MANAGERIAL ACCOUNTING (4),ACC 202,MANAGERIAL ACCOUNTING (3)
ACC120,RINCIPLES OF FINANCIAL ACCOUNTING (CAA) (4),ACC 201,FINANCIAL ACCOUNTING
...,...,...,...
SPA111,LEMENTARY SPANISH I (CAA) (3),SPA 101,BEGINNING SPANISH I
SPA112,LEMENTARY SPANISH II (CAA) (3),SPA 102,BEGINNING SPANISH II
SPA141,ULTURE & CIVILIZATION (CAA) (3),SPA 000,SPANISH ELECTIVE
SPA211,NTERMEDIATE SPANISH I (CAA) (3),SPA 203,INTERMEDIATE SPANISH I
SPA212,NTERMEDIATE SPANISH II (CAA) (3),SPA 204,INTERMEDIATE SPANISH II

In [63]:
common = list(caa.index.intersection(eq.index.unique()))
len(common)

469

In [64]:
common_df = eq.loc[common]

In [65]:
common_df

                                   caa_title  uncg_id               uncg_title
caa_id
ART-235                FIGURE DRAWING II (3)  ART 000             ART ELECTIVE
ART-240                       PAINTING I (3)  ART 000             ART ELECTIVE
ART-241                      PAINTING II (3)  ART 000             ART ELECTIVE
ART-242  INTERMEDIATE COMPUTER ANIMATION (3)  ART 000             ART ELECTIVE
ART-243                PORTRAIT PAINTING (3)  ART 000             ART ELECTIVE
...                                      ...      ...                      ...
SPA-212          INTERMEDIATE SPANISH II (3)  SPA 204  INTERMEDIATE SPANISH II
SPA-221             SPANISH CONVERSATION (3)  SPA 000         SPANISH ELECTIVE
SPA-231          READING AND COMPOSITION (3)  SPA 000         SPANISH ELECTIVE
SPA-281                    SPANISH LAB 3 (1)  SPA 000              SPANISH LAB
SPA-282                    SPANISH LAB 4 (1)  SPA 000              SPANISH LAB

[469 rows x 3 columns]

In [67]:
remaining = caa.loc[caa.index.difference(eq.index)]

In [68]:
remaining

,caa_course_title,Unnamed: 2,Unnamed: 3,Unnamed: 4
AST-111A,Descriptive Astronomy Lab,UGETC: Natural Sciences â€“ AA,NaN,NaN
AST-151A,General Astronomy I Lab,UGETC: Natural Sciences â€“ AA/AS,NaN,NaN
AST-152A,General Astronomy II Lab,GEN ED: Natural Science,NaN,NaN
BIO-140A,Environmental Biology Lab,GEN ED: Natural Science,NaN,NaN
CHM-115A,Concepts in Chemistry Lab,Pre-Major/Elective,NaN,NaN
CHM-130A,"Gen, Org, & Biochemistry Lab",Pre-Major/Elective,NaN,NaN
CHM-131A,Introduction to Chemistry Lab,GEN ED: Natural Science,NaN,NaN
EDU-131A,"Child, Family, and Community Lab",Pre-Major/Elective,NaN,NaN
EGR-120---------Eng-and-Design-Graphics-------------------------------Pre-Major/Elective,NaN,NaN,NaN,NaN
EGR-214,Numerical Methods for Engineers,Pre-Major/Elective,NaN,NaN
GER-231,Reading and Composition,Pre-Major/Elective,NaN,NaN
HIS-237,The American Revolution,Pre-Major/Elective,NaN,NaN
HIS-275,History of Terrorism,Pre-Major/Elective,NaN,NaN
IRI-111,Elementary Irish I,Pre-Major/Elective,NaN,NaN
IRI-112,Elementary Irish II,Pre-Major/Elective,NaN,NaN
IRI-211,Intermediate Irish I,Pre-Major/Elective,NaN,NaN
IRI-212,Intermediate Irish II,Pre-Major/Elective,NaN,NaN
ITA-231,Reading and Composition,Pre-Major/Elective,NaN,NaN
PHY-110A,Conceptual Physics Lab,UGETC: Natural Sciences â€“ AA/AS,NaN,NaN
POR-141,Culture and Civilization,Pre-Major/Elective,NaN,NaN
POR-221,Portuguese Conversation,Pre-Major/Elective,NaN,NaN
POR-231,Reading and Composition,Pre-Major/Elective,NaN,NaN
POR-281,Portuguese Lab III,Pre-Major/Elective,NaN,NaN
POR-282,Portuguese Lab IV,Pre-Major/Elective,NaN,NaN
RUS-231,Reading and Composition,Pre-Major/Elective,NaN,NaN

In [70]:
# remaining.to_excel("../output/remaining.xlsx")

In [71]:
# common_df.to_excel("../output/known.xlsx")